### ISSUE TITLE
Custom date font not working (regardless of font)

### ISSUE THREAD

**Issue by ccrowles** [tjaart/plasma-fancy-clock#9]
I've tried quite a bunch of custom font, even very noticeably different ones to be sure, but it appears that while the time font works perfectly (I have it as a separate widget with the same font), the date font doesn't want to budge from the system one.

![Screenshot_2020_06_20_212752](https://user-images.githubusercontent.com/12866474/85210081-47f77c80-b33d-11ea-9c38-6b3493611708.jpg)

If it's of any help:
![Screenshot_2020_06_20_213157](https://user-images.githubusercontent.com/12866474/85210120-8856fa80-b33d-11ea-84df-bf113413630a.jpg)

**Comment by tjaart** [comment]
It should work with the latest release.
